import type { Deployment } from "../core/types.js";
import { formatRemaining } from "../core/ttl.js";

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}

/**
 * Generates a simple static HTML dashboard for a set of deployments (spec
 * section 9). Optional — never required by the core deploy/preview flow.
 */
export function generateDashboardHtml(projectName: string, deployments: Deployment[]): string {
  const rows = deployments
    .map((d) => {
      const label = d.source.ref.replace(/^design\//, "");
      const statusBadge = d.status === "active" ? "READY" : d.status.toUpperCase();
      return `
      <tr>
        <td>${escapeHtml(label)}</td>
        <td class="status status-${escapeHtml(d.status)}">${escapeHtml(statusBadge)}</td>
        <td>${d.urls.preview ? `<a href="${escapeHtml(d.urls.preview)}" target="_blank" rel="noopener">Open Preview</a>` : "—"}</td>
        <td><a href="${escapeHtml(d.urls.repository)}" target="_blank" rel="noopener">Repository</a></td>
        <td>${escapeHtml(new Date(d.lifecycle.createdAt).toLocaleString())}</td>
        <td>${escapeHtml(new Date(d.lifecycle.expiresAt).toLocaleString())} (${escapeHtml(formatRemaining(d.lifecycle.expiresAt))})</td>
        <td>${d.source.commit ? `<code>${escapeHtml(d.source.commit.slice(0, 7))}</code>` : "—"}</td>
      </tr>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(projectName)} — Previews</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; background: #f7f7f8; color: #1a1a1a; }
  h1 { font-size: 1.25rem; }
  table { border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  th, td { padding: 0.6rem 0.9rem; text-align: left; border-bottom: 1px solid #eee; font-size: 0.9rem; }
  th { background: #fafafa; text-transform: uppercase; font-size: 0.72rem; letter-spacing: 0.04em; color: #666; }
  .status-active { color: #0a7d2c; font-weight: 600; }
  .status-failed { color: #b3261e; font-weight: 600; }
  footer { margin-top: 1rem; font-size: 0.8rem; color: #888; }
</style>
</head>
<body>
  <h1>${escapeHtml(projectName)} — Client Previews</h1>
  <table>
    <thead>
      <tr><th>Branch</th><th>Status</th><th>Preview</th><th>Repository</th><th>Deployed</th><th>Expires</th><th>Commit</th></tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <footer>Generated by github-deployment-infrastructure. Previews are temporary and will be deleted automatically after expiry.</footer>
</body>
</html>
`;
}
