import type { BuildConfig, Framework } from "../../core/types.js";
import { installCommand, runScript, type PackageManager } from "../../framework/package-manager.js";

export interface WorkflowContext {
  build: Required<Pick<BuildConfig, "command" | "output">>;
  framework: Framework;
  /** The repository name the site will be served under: https://OWNER.github.io/REPO/ */
  repositoryName: string;
  nodeVersion?: string;
  /**
   * The detected package manager, or "none" when no lockfile is present.
   * actions/setup-node's cache option must match the actual lockfile type —
   * "npm" cannot read pnpm-lock.yaml/yarn.lock, so this drives both the
   * cache option and (for pnpm) an extra pnpm/action-setup step that must
   * run before actions/setup-node.
   */
  packageManager: PackageManager;
}

/** Frameworks that are typically SPAs and benefit from a 404.html fallback for client-side routing. */
const SPA_FALLBACK_FRAMEWORKS: Framework[] = ["STATIC", "VITE", "GENERIC"];

/**
 * Generates the GitHub Actions workflow that builds and deploys a preview
 * to GitHub Pages (spec section 11). Uses official GitHub Pages actions
 * exclusively — actions/checkout, actions/configure-pages,
 * actions/upload-pages-artifact, actions/deploy-pages — pinned to major
 * version tags published by GitHub. Operators who require SHA pinning can
 * swap the `uses:` lines for the SHA of the same tag.
 */
export function generatePagesWorkflow(ctx: WorkflowContext): string {
  // Node 20 is EOL/deprecated on GitHub-hosted runners, and modern pnpm
  // releases (pnpm/action-setup with no pinned version resolves whatever a
  // project's package.json#packageManager pins) commonly require Node
  // >=22.13 — using it as the default silently breaks pnpm projects with a
  // Node-internal error, not a clear "unsupported Node version" message.
  const nodeVersion = ctx.nodeVersion ?? "22";
  const hasBuildStep = ctx.build.command && ctx.build.command !== "true";
  const pm = ctx.packageManager;

  // Vite supports overriding the base path via a CLI flag, so we can inject
  // the GitHub Pages project-site base path (spec section 13) without
  // touching the project's own vite.config. Other frameworks (Astro,
  // Next static export, Nuxt) require base/site config in their own config
  // files; PAGES_BASE_PATH is exported as an env var so those config files
  // can read it (documented in README "GitHub Pages limitations").
  const conventionalBuildCommand = runScript(pm, "build");
  const buildCommand =
    ctx.framework === "VITE" && ctx.build.command === conventionalBuildCommand
      ? `${conventionalBuildCommand} -- --base="$PAGES_BASE_PATH"`
      : ctx.build.command;

  // actions/setup-node's built-in cache option only understands npm/yarn's
  // own lockfiles; pnpm requires pnpm itself to be on PATH *before*
  // actions/setup-node runs (via pnpm/action-setup), at which point
  // `cache: pnpm` works. "none" omits the cache option entirely — enabling
  // it with no lockfile hard-fails the run rather than degrading gracefully.
  const pnpmSetupStep =
    pm === "pnpm"
      ? `      - name: Set up pnpm
        uses: pnpm/action-setup@v4

`
      : "";
  const cacheLine = pm === "pnpm" || pm === "yarn" || pm === "npm" ? `\n          cache: ${pm}` : "";

  const buildSteps = hasBuildStep
    ? `${pnpmSetupStep}      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${nodeVersion}"${cacheLine}

      - name: Install dependencies
        run: ${installCommand(pm)}

      - name: Build
        env:
          PAGES_BASE_PATH: "/${ctx.repositoryName}/"
        run: ${buildCommand}
`
    : "";

  const spaFallbackStep = SPA_FALLBACK_FRAMEWORKS.includes(ctx.framework)
    ? `
      - name: Add SPA 404 fallback
        run: cp "${ctx.build.output}/index.html" "${ctx.build.output}/404.html" 2>/dev/null || true
`
    : "";

  return `# Generated by github-deployment-infrastructure. Do not edit manually —
# changes are overwritten on the next \`gdi update\`.
name: Deploy preview to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

${buildSteps}${spaFallbackStep}
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${ctx.build.output}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}
