import type { BuildConfig, Framework } from "../../core/types.js";

export interface WorkflowContext {
  build: Required<Pick<BuildConfig, "command" | "output">>;
  framework: Framework;
  /** The repository name the site will be served under: https://OWNER.github.io/REPO/ */
  repositoryName: string;
  nodeVersion?: string;
  /** Whether a package manager lockfile is present — actions/setup-node's cache option fails outright without one. */
  hasLockfile: boolean;
}

/** Frameworks that are typically SPAs and benefit from a 404.html fallback for client-side routing. */
const SPA_FALLBACK_FRAMEWORKS: Framework[] = ["STATIC", "VITE", "GENERIC"];

/**
 * Generates the GitHub Actions workflow that builds and deploys a preview
 * to GitHub Pages (spec section 11). Uses official GitHub Pages actions
 * exclusively — actions/checkout, actions/configure-pages,
 * actions/upload-pages-artifact, actions/deploy-pages — pinned to major
 * version tags published by GitHub. Operators who require SHA pinning can
 * swap the `uses:` lines for the SHA of the same tag.
 */
export function generatePagesWorkflow(ctx: WorkflowContext): string {
  const nodeVersion = ctx.nodeVersion ?? "20";
  const hasBuildStep = ctx.build.command && ctx.build.command !== "true";

  // Vite supports overriding the base path via a CLI flag, so we can inject
  // the GitHub Pages project-site base path (spec section 13) without
  // touching the project's own vite.config. Other frameworks (Astro,
  // Next static export, Nuxt) require base/site config in their own config
  // files; PAGES_BASE_PATH is exported as an env var so those config files
  // can read it (documented in README "GitHub Pages limitations").
  const buildCommand =
    ctx.framework === "VITE" && ctx.build.command === "npm run build"
      ? `npm run build -- --base="$PAGES_BASE_PATH"`
      : ctx.build.command;

  const cacheLine = ctx.hasLockfile ? "\n          cache: npm" : "";

  const buildSteps = hasBuildStep
    ? `      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${nodeVersion}"${cacheLine}

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        env:
          PAGES_BASE_PATH: "/${ctx.repositoryName}/"
        run: ${buildCommand}
`
    : "";

  const spaFallbackStep = SPA_FALLBACK_FRAMEWORKS.includes(ctx.framework)
    ? `
      - name: Add SPA 404 fallback
        run: cp "${ctx.build.output}/index.html" "${ctx.build.output}/404.html" 2>/dev/null || true
`
    : "";

  return `# Generated by github-deployment-infrastructure. Do not edit manually —
# changes are overwritten on the next \`gdi update\`.
name: Deploy preview to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

${buildSteps}${spaFallbackStep}
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${ctx.build.output}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}
